#include <catch2/catch_test_macros.hpp>
#include <Event/Event.hpp>

aeyon::Event event;

TEST_CASE("GUID generated by default constructor is defined", "[events]")
{
    REQUIRE(!event.getGUID().isNil());
}